version: "3.8"
services:

  web:
    image: mapio/dt-app
    build: ../build
    ports:
      - "80:80"
    networks:
      - dt-network

  redis:
    image: redis
    volumes:
      - dt-data:/data
    command: redis-server --appendonly yes
    networks:
      - dt-network

volumes:
  dt-data:

networks:
  dt-network:
